version: "3"

services:
  db:
    image: mariadb:10.5
    container_name: ai_chat_db
    volumes:
      - "/xxx/ai-chat/mysql-data:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev
      - MYSQL_LOG_CONSOLE=true
      - lower_case_table_names=1
